package constants

const (
	SPOTIFY_ID_ENV   = "SPOTIFY_ID"
	SPOTIFY_SEC_ENV  = "SPOTIFY_SECRET"
	SPOTIFY_LINK_KEY = "spotify"

	UCC_SHOW_ID = "3vuV292Him90EjQ5YL4XIw"

	TWITTER_API_KEY          = "TWTR_API_KEY"
	TWITTER_API_KEY_SEC      = "TWTR_API_KEY_SEC"
	TWITTER_ACCESS_TOKEN     = "TWTR_ACCESS_TOKEN"
	TWITTER_ACCESS_TOKEN_SEC = "TWTR_ACCESS_TOKEN_SEC"
)
